name: ML Pipeline CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov flake8 httpx
        pip install -e .
        
    - name: Run linting
      run: |
        flake8 src/ tests/ --count --select=E9,F63,F7,F82 --show-source --statistics
        
    - name: Run unit tests with coverage
      run: |
        pytest tests/ --cov=src/ --cov-report=xml
        
    - name: Run model training and validation
      run: |
        python -m mlops_diabetes.train
        python -m mlops_diabetes.validate_model --threshold-r2 0.4 --threshold-mse 3000
        
    - name: Cache model artifacts
      uses: actions/cache@v3
      with:
        path: models/
        key: ${{ runner.os }}-model-${{ github.sha }}
        
  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v3  
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov flake8 httpx
        pip install -e .

    - name: Run tests and coverage
      run: |
        pytest tests/ --cov=src/ --cov-report=xml
        
    - name: Run linting
      run: |
        flake8 src/ tests/ --count --select=E9,F63,F7,F82 --show-source --statistics
    
    - name: Restore model artifacts
      uses: actions/cache@v3
      with:
        path: models/
        key: ${{ runner.os }}-model-${{ github.sha }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER_NAME }}
        password: ${{ secrets.DOCKER_PASS_TOKEN }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_USER_NAME }}/mlops-diabetes:latest
          ${{ secrets.DOCKER_USER_NAME }}/mlops-diabetes:${{ github.sha }}
        cache-from: type=registry,ref=${{ secrets.DOCKER_USER_NAME }}/mlops-diabetes:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKER_USER_NAME }}/mlops-diabetes:buildcache,mode=max
        build-args: |
          PYTHON_VERSION=3.9
          BUILD_ENV=production
        
    - name: Verify Docker image
      run: |
        # Pull and test the built image
        docker pull ${{ secrets.DOCKER_USER_NAME }}/mlops-diabetes:${{ github.sha }}
        
        # Run the container and test the health endpoint
        docker run -d --name test-api -p 8000:8000 ${{ secrets.DOCKER_USER_NAME }}/mlops-diabetes:${{ github.sha }}
        
        # Wait for container to be ready
        sleep 10
        
        # Test health endpoint
        curl -f http://localhost:8000/health || exit 1
        
        # Show container logs if health check fails
        if [ $? -ne 0 ]; then
          docker logs test-api
          exit 1
        fi
        
        # Cleanup
        docker stop test-api
        docker rm test-api

  deploy-staging:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment: staging
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    
    - name: Deploy to staging ECS
      run: |
        aws ecs update-service \
          --cluster staging-cluster \
          --service diabetes-api-staging \
          --force-new-deployment \
          --task-definition diabetes-api-staging:latest
        
    - name: Wait for ECS deployment
      run: |
        aws ecs wait services-stable \
          --cluster staging-cluster \
          --services diabetes-api-staging
        
    - name: Run integration tests
      run: |
        # Install test dependencies
        pip install pytest requests
        # Run integration tests against staging endpoint
        pytest tests/integration/ --staging-url=https://staging-api.example.com
        
  deploy-production:
    needs: deploy-staging
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment: 
      name: production
      url: https://api.example.com
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    
    - name: Deploy to production ECS
      run: |
        aws ecs update-service \
          --cluster production-cluster \
          --service diabetes-api-production \
          --force-new-deployment \
          --task-definition diabetes-api-production:latest
        
    - name: Wait for ECS deployment
      run: |
        aws ecs wait services-stable \
          --cluster production-cluster \
          --services diabetes-api-production
        
    - name: Verify deployment
      run: |
        # Install curl
        sudo apt-get update && sudo apt-get install -y curl
        # Wait for endpoint to be available
        for i in {1..30}; do
          if curl -f https://api.example.com/health; then
            echo "Deployment verified successfully"
            exit 0
          fi
          echo "Waiting for endpoint to be available... attempt $i"
          sleep 10
        done
        echo "Deployment verification failed"
        exit 1 